name: Windows MSVC CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Setup ENV
      run: |
        echo "CI=false" >> "$GITHUB_ENV"
    - name: Test No-Op (debug)
      run: cl /Od /RTCsu /TC tests\noop.c /I. /D_CRT_NONSTDC_NO_WARNINGS /DFIO_LEAK_COUNTER=1 /DDEBUG /Fe./noop.exe && ./noop.exe
    - name: Test STL (debug) - no allocators
      run: cl /Od /RTCsu /TC tests\stl.c /I. /D_CRT_NONSTDC_NO_WARNINGS /DFIO_MEMORY_DISABLE=1 /DFIO_LEAK_COUNTER=1 /DDEBUG /Fe./stld.exe && ./stld.exe
    - name: Test Mustache Compliance (debug) - no allocators
      run: cl /Od /RTCsu /TC tests\mustache.c /I. /D_CRT_NONSTDC_NO_WARNINGS /DFIO_MEMORY_DISABLE=1 /DFIO_LEAK_COUNTER=1 /DDEBUG /Fe./stld.exe && ./stld.exe
    - name: Test fio_malloc speed
      run: cl /O2 /Oi /TC tests\malloc.c /I. /Fe./malloc.exe && ./malloc.exe
    - name: Test STL
      run: cl /O2 /Oi /TC tests\stl.c /D_CRT_NONSTDC_NO_WARNINGS /DFIO_LEAK_COUNTER=1 /I. /Fe./stl.exe && ./stl.exe
