name: Windows Clang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - uses: egor-tensin/setup-clang@v1
      with:
        platform: x64
    - name: Setup ENV
      run: |
        echo "CI=false" >> "$GITHUB_ENV"
    - name: Test No-Op (debug)
      run: clang -O0 -Wno-#pragma-messages -fstack-protector-all tests\noop.c -I. -DFIO_LEAK_COUNTER=1 -DDEBUG -D_CRT_NONSTDC_NO_WARNINGS -o ./noop.exe && ./noop.exe
    - name: Test STL (debug) - no allocators
      run: clang -O0 -Wno-#pragma-messages -fstack-protector-all tests\stl.c -I. -DFIO_MEMORY_DISABLE=1 -DFIO_LEAK_COUNTER=1 -D_CRT_NONSTDC_NO_WARNINGS -DDEBUG -o ./stl_d.exe && ./stl_d.exe
    - name: Test fio_malloc speed
      run: clang -O3 -Wno-#pragma-messages -march=native tests\malloc.c -I. -o ./malloc_spd_tst.exe && ./malloc_spd_tst.exe
    - name: Test STL
      run: clang -O3 -Wno-#pragma-messages -march=native tests\stl.c -DFIO_LEAK_COUNTER=1 -D_CRT_NONSTDC_NO_WARNINGS -I. -o ./stl_r.exe && ./stl_r.exe
